language: python
sudo: false
python:
  - "3.7"

install: "pip install pep8 coveralls"
before_script:
  - "pep8 --ignore=E501 py_skiplist/"
# command to run tests
script: coverage run --source py_skiplist -m unittest discover tests "*_tests.py"

after_success:
  coveralls
